### ISSUE TITLE
TakePhoto error with SL1/100D

### ISSUE THREAD

**Issue by ale770** [kritzikratzi/edsdk4j#17]
Hello

I'm getting an error sometimes when i take the photo. Sometimes it works fine but some other times it doesn't.

I call the shoot command, it processes the method run() and finishes it with ERR_OK.
It enters the final if on the mehtod run();
if ( err == EdsError.EDS_ERR_OK ) {
     //System.out.println( "Took image, waiting for camera" );   	
     notYetFinished();
}
But after that, nothing. It never goes into the mehtod apply().

I'm invoking the take picture method with: 
final File[] photos = camera.shoot(EdsSaveTo.kEdsSaveTo_Host);

Do you have any tips on what i could check or what could be going wrong?

Sorry for my english..

Thanks.

**Comment by ale770** [comment]
Sorry for the delay.

When it works fine the counts are:
Line 103: Count = 1
Line 170: Count = 0

And when it doesn't
Line 103: Count = 1;
Line 170: Never reaches it.

**Comment by ale770** [comment]
I'm starting to think its a problem with the camera.

This problem occurred with the SL1 model, now i'm using a T3i and i had no problems so far.

**Comment by kritzikratzi** [comment]
good to hear. i've been using the api quite a bit recently with a 600d (same as the t3i i think), and haven't had any problems. 

i've renamed the bug to include your previously used model. if i ever get hold of one i'll see if i can find something that causes the problem. 

thanks for your status update!

**Comment by WolfgangFahl** [comment]
Please let us know if the latest version still has this issue and we'll reopen this issue.
