### ISSUE TITLE
Cannot find CanonUtils.class [from Oliver Ellmers]

### ISSUE THREAD

**Issue by kritzikratzi** [kritzikratzi/edsdk4j#18]
Oliver Elmers: 
[quote]
I am currently building an application with your edsdk library for processing, where I need control over a 5D MK2 EOS camera.

The example sketches and my own sketch cannot find the edsdk.utils.CanonConstants class. 

I was wondering if either of you two would be able to shine some light on my situation.

All the best!
[/quote]

**Comment by kritzikratzi** [comment]
hey! can you please describe a bit more about what you are trying to do, 
how you set up your classpath and what exact error you are getting?

**Comment by oliverellmers** [comment]
Hey there!

Thanks for the response.

I am trying to control the EOS cameras features such as deleting after download, setting image directory, focussing, color spaces etc via processing. But the utils.canonConstants library cannot be found.

Is this enough information?

library path:
D:\Working Directories\Development\Processing Sketchbook\libraries\edsdk\library\
![libpath](https://cloud.githubusercontent.com/assets/3712043/5957328/ff7f74fe-a80b-11e4-9e5f-8e92f3b91da9.png)

canon utils path:
D:\Working Directories\Development\Processing Sketchbook\libraries\edsdk\src\edsdk\utils\CanonConstants.java
![canonconstantspath](https://cloud.githubusercontent.com/assets/3712043/5957330/07f8d85a-a80c-11e4-815a-015aec1a0fb5.png)

Error:
The function setDeleteJpegAfterDownload(boolean) does not exist
No library found for edsdk.utils.CanonConstants
![Uploading error.png . . .]()

Best,

O.

**Comment by kritzikratzi** [comment]
aaah, this is about the processing version. 
is it possible you've simply forgotten to import the library? 

can you try using the sketch menu, from there select
import library >> edsdk

**Comment by oliverellmers** [comment]
The library has definitely been imported correctly, as I am successfully taking photographs with the edsdk. It is only the utile.canonconstants class / library that cannot be found - the import lines of text are at the top of the sketch, you cannot see them in the above screen shot.

When I comment out the functions that require the canonconstants lib, I am able to take photographs fine. I just cannot set image directories, or delete after shooting etc.

O.

**Comment by kritzikratzi** [comment]
hm... maybe i made an error when exporting the library. 
not sure i have time today, but i'll take a look, latest tomorrow !

**Comment by oliverellmers** [comment]
awesome thanks a bunch for that, really appreciate your help :)

**Comment by kritzikratzi** [comment]
hey! 

> http://asdfg.me/up/edsdk-processing/snippets/index.html

There was an error in the documentation, the command is `setDeleteJpgAfterDownload` (Jpg, not Jpeg). 
I've fixed it. Can you try again?

**Comment by oliverellmers** [comment]
AHA! It seems to be working now! Thank you for your help!

I am still however receiving the "No library found for edsdk.utils.CanonConstants
" error, although everything is working fine now..

**Comment by kritzikratzi** [comment]
yep, was a known bug when using `import static`. see https://github.com/processing/processing/issues/8 

but i'm not sure if the fix is in the latest processing 2.x series, or if you have to wait for processing 3.
