### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by dgbc** [kritzikratzi/edsdk4j#19]
It's not an issue but a question.
How can I use zoom features during liveview mode?
Any example is helpful.

Thanks

**Comment by kritzikratzi** [comment]
it goes something like this: 

1. set your focus switch on the camera to AF
2. start live view
3. set focus mode to manual (in software, use camera.setFocusMode(MANUAL))
4. use the focus commands for near/far


does this help?

**Comment by dgbc** [comment]
Thanks for the reply.
It's not quite what I want to achieve.
I'm using E04_LiveView.java as the starting point and I want to create a "zoom" button to toggle the live view zoom. I also created buttons: up, down, left and right, so I can move the zoomed rectangle.
Why does camera.downloadLiveView() always return a 960 x 640 BufferedImage ?

I'm able to scale the BufferedImage but the LiveView just get very slow if I use an old camera.
I hope my question makes sense.. 

Thanks for your help.

**Comment by kritzikratzi** [comment]
> Why does camera.downloadLiveView() always return a 960 x 640 BufferedImage ?
i think that depends on the camera model. 
it might be different on different cameras. 
anyways, it can't be changed. 

> I'm using E04_LiveView.java as the starting point and I want to create a "zoom" button to toggle the live view zoom. I also created buttons: up, down, left and right, so I can move the zoomed rectangle.
sorry, was reading your initial question to quickly. 
there's a pdf document that comes with the sdk (EDSDK_API.pdf), have you checked if you can find the zoom function there? 


best, hansi.

**Comment by kritzikratzi** [comment]
ps. yes, liveview over usb is pretty slow. i think the only way to improve this is by using the hdmi out and a hdmi capture card. but i haven't tried that.
