### ISSUE TITLE
Issue with Error 99 on EOS 50D

### ISSUE THREAD

**Issue by Infineon12** [kritzikratzi/edsdk4j#20]
Hi there, first of all thank you for your library!

I got a 50D and got it working to capture images on request, live view etc.
But the transfer of the captured image took to long so i wanted to lower the image quality.

I used the E06_ListImageQuality to list all the qualities and choosed one.
Before the next capture the quality was set and there happened an exception.

Since this moment my cam is kinda broken. Every time i turn it on it says Error 99. 
I did battery resets and nearly everything found in the internet.
I realized that i am able to go into the custom modes C1 and C2, there i can shoot pictures etc.
I also could reflash the firmware from the menu while in C Mode.
But everytime i switch back to another mode it always tells me Error 99.
I cannot make a factory reset cause this is not possible within C Mode Menus.

So anyone has an idea what i should do!?
My last hope currently is to send the camera to Canon, but i would love to prevent this if possible.

My idea of what happened is that maybe the camera quality i selected made an issue and is now the default setting. Within the custom modes there is a different setting and no problem.

For any help thanks in advance!

**Comment by kritzikratzi** [comment]
hey! 


oh god, that sounds horrible. tbh, i've never seen or heard of that error before. 
can you still connect to the camera using the edsdk? 
i'd attempt to set it to another image mode, and see if that fixes it.

afaik with the edsdk it's possible to set properties to illegal values, which can certainly confuse the camera. so maybe you can fix it by setting it back to something the camera likes. 

best, hansi.

**Comment by Infineon12** [comment]
Thanks for your fast answer. I can connect but only if i am in the C1 and C2 Modes. Within the other ones where i have the issue the device is not recognized by usb.

**Comment by kritzikratzi** [comment]
What's C1/C2? (i dont have a 50D)

**Comment by Infineon12** [comment]
On the mode Selection wheel there are C1 C2 and on some cams also C3.
These are user specific custom settings where you can configure everything different and save.

**Comment by kritzikratzi** [comment]
in which mode where you when you set the image quality? 


i _believe_ what happened is that put the quality setting (or another property) to a value not applicable for your camera (for whatever reason). i think those values get written to the EEPROM, thats why removing the batteries won't help. i'm not even sure this memory gets reset when you do a firmware reset. reset to factory settings should do the trick. (and i think this should be easy for canon to do, even if the camera appears bricked at the moment). 

1. if you run the E06 example from the gettingstarted folder, which sizes does it report? 
2. can you post the code you used to put your camera in this sad state to pastebin? knowing what happened exactly would certainly help. 


best, h

**Comment by Infineon12** [comment]
Image Qualities: http://pastebin.com/EKkfqtKy

I choosed EdsImageQuality_LR/6618895

Code : http://pastebin.com/UbQuTrjS

For explanation its a marriage photobox.
So you got a live view and after a countdown a picture will get taken.
This works without setting the image quality.

----

Yeah i am quite sure that canon is able to reset this, but its really annoying that i cant.

**Comment by kritzikratzi** [comment]
did you manage to fix this in the end?

**Comment by Infineon12** [comment]
No not really, the camera is currently send to canon and i am waiting for the estimated repair costs.
Even if the camera is fixed and returned i think i wont try it again to not risk another defect.

So will give an update when and if canon tells me the reason for this issue.

Greetings

**Comment by kritzikratzi** [comment]
ok. i hope it turns out not too bad. 
once you get the camera back i'd be very happy if you could post how canon handled the situation (like how long it took them, if they charged you, and so on). 
tbh, i've never heard of this happening before, it's something people should definitely be aware about.

**Comment by Infineon12** [comment]
Hi there, just recieved the estimated costs. ~420€

They want to replace the electronical line system and need to readjust.
In my oppinion this is a total rip off.
Cause the camera is not mine, lend from a close friend, i will need to accept this and try to get the money back from my insurance.

**Comment by kritzikratzi** [comment]
wait, what the ...? checking on amazon i see that you can get a used 50D starting at 350-400. 
ps are you based in austria by any chance? i see some german words on your github account.

**Comment by Infineon12** [comment]
i am german :)

so yeah the issue with used cams at ebay etc. is that they also can be in need of a lense calibration etc. which could need a send in to canon.

so the costs are
150€ person costs
186,10€ material costs
16,90€ delivery
all prices above are net prices

they also mention that they need to clean the camera and recalibrate the sensors etc.

in my oppinion they want to shock and hope that some persons say "okay wait then i just buy a brand new camera"

sad!

**Comment by kritzikratzi** [comment]
ah, so i can't just come over and take a look. 
well, if you wanna have a last attempt at fixing it using skype+teamviewer contact me. i'm really busy at the moment, but i could definitely spare an hour or two tomorrow. just write an email to alksdjfsadfkjasdfhasdkfj@superduper.org

**Comment by Infineon12** [comment]
Thanks for your support!

But the camera is at canon and i cant access it until i decide to either repair, send back without repair or trash it.

**Comment by kritzikratzi** [comment]
ok, just let me know. (if you write me an email please post "wrote you an email" here so i know to check the spam folder). 

ps. i have added a section about this problem to the readme. https://github.com/kritzikratzi/edsdk4j

**Comment by Infineon12** [comment]
I just recieved the fixed camera back. The price stayed like mentioned. Everything is working, at least.

Thanks for your help.

**Comment by kritzikratzi** [comment]
thanks for your continuous updates!

**Comment by kritzikratzi** [comment]
enough time has passed and it seems no one else reported a similar problem. 
closing this in the hope that it was a freak accident.

**Comment by vidyapiquor** [comment]
CanonCamera.EDSDK.EdsCreateMemoryStream( new NativeLong( 0 ), streamRef )  is giving error while trying to run " E04_LiveView  " of edsdk4j .  please help

**Comment by kritzikratzi** [comment]
@vidyapiquor please don't post unrelated comments on a closed bug. feel free to open a new bug, but gather some more info (what's the error, for instance). this is a bug tracker (there is no support forum. some things you'll have to figure out yourself).
