### ISSUE TITLE
Java(TM) SE binary has stopped working

### ISSUE THREAD

**Issue by JerDha** [kritzikratzi/edsdk4j#22]
Hi,
Really grateful for what you've done with this! Very helpfull and great to use.
I've tried your examples and then started my own small project.
In combination with a JavaFX UI I'm trying to make a small easy to use photobooth, to use on a friends party.

I have 'some' experience in Java but not that much with threads and external libraries/wrappers. The problem I have is that most of the times (not everytime) when I call the 'shoot' command I get the above mentioned error... no exceptions or other errors, just my app crashes and I get the 'Java(TM) SE binary stopped working.'... I already tried a few things, also the shootAsync gives me the same issue.

Strange thing is that sometimes it just works... (but that's like 1/10 or even less)
Now I use it in it's simplest form (I think):
`File file = new File("C:/.../Desktop/test.jpg");
camera.openSession();
camera.shoot(EdsSaveTo.kEdsSaveTo_Host, 3, file);
camera.closeSession();`
My camera (EOS 550D) actually takes the picture, and then gives the error.

Also sometimes the picture gets saved to the desired location as '...Desktop/test.jpg' but most of the times it doesn't (but that looks like another problem?).

When I try the liveView I have no troubles. I can start it and stop it and start it again... (also in my JavaFX UI).

So I'm not sure what the problem is...
I've already downloaded the latest jre and jdk (or could that be the issue), or could it be something else... Maybe you (or someone) already encountered this issue?

Best regards

**Comment by kritzikratzi** [comment]
"binary stopped working" means there is some serious error inside edsdk.dll. 

did you try running the examples in the `gettingstarted` package?

**Comment by JerDha** [comment]
Yes I did.
The only time this issue raises in the gettingstarted package is on the E05_Timelapse... (on closing it).
Sometimes I get the `java.io.ioexception the filename directory name or volume label syntax is incorrect` but I don't think that's related?

**Comment by WolfgangFahl** [comment]
Which version of Java are you using? Is this a 32 bit or 64 bit environment? 
You might want to try out the current 0.0.1 version which has some JUnit Tests and add your crashing code lines as a new JUnit Test. To do so please fork the repository add your test and create a pull request.

**Comment by JerDha** [comment]
I was using a 64-bit environment...
And as I understood from some documentation I've read the provided libraries for 64 bit were/are not stable (especially handling the files) so I believe this was the problem...
Since I started a whole other approach for my project (not a java app anymore but a combination of python scripts on my raspberry pi) I haven't tried to switch to the 32-bit version or further look into the issues I had.

**Comment by WolfgangFahl** [comment]
Thanx - as part of trying to get MaxOSX support we intend to use upgraded libraries soon.

**Comment by WolfgangFahl** [comment]
The current version is for EDSDK V3.4 - just let us know if you still have issue with this and I'll reopen this issue.
