### ISSUE TITLE
publish on maven central

### ISSUE THREAD

**Issue by WolfgangFahl** [kritzikratzi/edsdk4j#25]
I am volunteering to add support for this. See e.g.
http://search.maven.org/#artifactdetails%7Ccom.bitplan%7Cw3cValidator%7C0.0.3%7Cjar for an example of a published maven artifact

**Comment by kritzikratzi** [comment]
i'm all for it, but i don't have any experience publishing maven artefacts.

**Comment by WolfgangFahl** [comment]
A first release has been done using the procedure described at:
https://github.com/kritzikratzi/edsdk4j/wiki/Release-procedure

**Comment by WolfgangFahl** [comment]
It might take a few hours before maven central is updated ...
