### ISSUE TITLE
Video Recording

### ISSUE THREAD

**Issue by RaveendraDhyani** [kritzikratzi/edsdk4j#3]
please provide functionalty to record video using edsdk as , canon mention in his documentation of version 2.13 that now we can record video from canon camera.

**Comment by Sx3** [comment]
Do you have any way to record a video yet :(

**Comment by Sx3** [comment]
@RaveendraDhyani are u able to record a video ?

**Comment by RaveendraDhyani** [comment]
No , I could not get success on this.

**Comment by kritzikratzi** [comment]
i have too many things to do at the moment so i can't look into it myself (also i exclusively use this for time lapse recordings, so i don't even have a need for video recording). 

i'm leaving this bug open though. if anyone can find a snippet to working c-code then please post it back here. maybe someone can find the time to investigate some more. 

also if you made a reasonable attempt but failed, it could still be interesting to let us know what you tried and how it failed. if you find the email updates annoying: there's an "unsubscribe" button on the right side (scroll up a bit).

**Comment by WolfgangFahl** [comment]
This is discussed at:

http://stackoverflow.com/questions/4037929/how-to-start-stop-video-recording-on-canon-camera-via-sdk

Getting the pictures from live view as an MJPEG stream is not a big thing. I am working on this today anyways.

**Comment by WolfgangFahl** [comment]
The videorecording function	public void recordVideo(FileOutputStream mjpegStream, int milliSeconds) is now available. It saves the LiveView JPEG images to an outpstream (which an be a file). To view the resulting file you might want to use VLC or use the https://github.com/BITPlan/com.bitplan.mjpegstreamer library.
