### ISSUE TITLE
Can't find where to put EDSDK.dll

### ISSUE THREAD

**Issue by terrymoes** [kritzikratzi/edsdk4j#4]
Hi,

I'm trying to set up an Eclipse workspace to try your library.
I've downloaded the SDK from Canon and your library.

I've copied your library somewhere on my harddrive, and put the complete EDSDK folder I've downloaded from Canon at the root of your folder.
[...]edsdk4j-master\EDSDK\Dll

I then created a new Eclipse Workscape and imported the edsdk4j project.
Except some warnings, Eclipse is not complaining about anything.

But when I'm trying to run one of your sample, execution inevitably fails when trying to load the EDSDK dll.

I've tried copying the complete EDSDK folder in several places with no success. I've also tried copying the DLL folder from EDSDK on the root of my hard drive and changing the path to the DLL in the source code with no effect.

Could you please help me with this issue?

Many thanks!
Best greetings,
Terry

**Comment by a3pelawi** [comment]
I'm using canon EOS 1200 D, first install EOS Utility on your windows, test your EOS Utility run or not. I'm using Live view from this utility.
And then, i clone from github https://github.com/kritzikratzi/edsdk4j
compile it using "ant", you can download it from apache ant, better if u search from google.
Find where your ant are installed, and then from command line, ant -buildfile C:\edsdk4j
If found error, Not find EDSDK or EDSDK_64 folder, skip that, check the folder C:\edsdk4j. Now you will find dist\edsdk4j-snapshot folder, u can use the edsdk.jar.
I'm use this file for my project using netbeans 8.

I try on my computer win 8 x64, I've install jdk 7 32 bit. Try to make simple project from netbeans, with jdk 7 32 bit as your sdk. Build it, u can test the code from sample from github. After u build your project from netbeans, find dist folder, find lib folder and create EDSDK/Dll folder inside it.
Copy EDSDK.dll and the other dll from eos canon utility installed. My .dll stored in folder C:\Program Files (x86)\Canon\EOS Utility\EU2

Note. My github clone for edsdk4j stored in C:\edsdk4j

Sory my english not good. I try it, and working well.
