### ISSUE TITLE
EsdSaveImage

### ISSUE THREAD

**Issue by SteveHodge** [kritzikratzi/edsdk4j#5]
I'm getting a ESD_ERR_NOT_SUPPORTED error from EsdSaveImage. Here's a simple case that fails (error checking for other calls has been removed but these calls all succeed provided you've got an input RAW file in the right place). Btw, you don't need a camera attached to run this.

	__EdsObject inStream[] = new __EdsObject[1];
	ByteBuffer name = ByteBuffer.allocate(100);
	name.put(Native.toByteArray("Test.CR2"));
	EDSDK.EdsCreateFileStream(name, EdSdkLibrary.EdsFileCreateDisposition.kEdsFileCreateDisposition_OpenExisting, EdSdkLibrary.EdsAccess.kEdsAccess_Read, inStream);

	__EdsObject imgRef[] = new __EdsObject[1];
	EDSDK.EdsCreateImageRef(inStream[0], imgRef);

	__EdsObject outStream[] = new __EdsObject[1];
	name = ByteBuffer.allocate(100);
	name.put(Native.toByteArray("output.jpg"));
	EDSDK.EdsCreateFileStream(name, EdSdkLibrary.EdsFileCreateDisposition.kEdsFileCreateDisposition_CreateAlways, EdSdkLibrary.EdsAccess.kEdsAccess_Write, outStream);

	EdsSaveImageSetting.ByValue set = new EdsSaveImageSetting.ByValue();
	set.JPEGQuality = new NativeLong(8);
	set.iccProfileStream = null;
	NativeLong err = EDSDK.EdsSaveImage(imgRef[0], EdSdkLibrary.EdsTargetImageType.kEdsTargetImageType_Jpeg, set, outStream[0]);
	System.out.printf("Save image error = 0x%x\n", err.intValue());

The C equivalent works as a console app. But putting the working C code into a dll and calling it from Java via JNI does not work. This makes me think there is something that EsdSaveImage is expecting from the calling environment that is missing when called from Java. But I don't know enough about that sort of low level Windows development to guess what it might be (I did try adding a CoInitalizeEx() call as mentioned in the SDK docs).

Incidentally the above code works with EDSDK 1.3, but not with any 2.x version I've tried.

**Comment by WolfgangFahl** [comment]
The loading of the dependen libraries goes by the default library paths which can be set if necessary. If such an issues show up with the latest V3.4 SDK just let us know and I'll reopen this issue.
